services:
  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  backend:
    command: bash -c "sleep 5 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app

  celery-worker:
    command: bash -c "sleep 10 && watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- celery -A app.tasks.scrape_trending worker --loglevel=info"
    volumes:
      - ./backend:/app
